name: 'Publish strand version'
description: "Publish a JSON schema as a new strand version."
author: 'cortadocodes'
branding:
  icon: anchor
  color: red

inputs:
  token:
    description: 'A Strands access token with permission to create a strand version for the given strand.'
    required: true
  account:
    description: 'The account handle for the strand to publish the schema to.'
    required: true
  name:
    description: 'The name of the strand to publish the schema to.'
    required: true
  path:
    description: 'The path to the JSON schema to publish as the new strand version (relative to the repository root).'
    required: true
  version:
    description: 'The semantic version to publish the strand version as. If not provided, the Strands app will choose the version automatically based on the changes made.'
    required: false
    default: ''
  notes:
    description: 'Any notes to add to the strand version.'
    required: false
    default: ''
  allow_beta:
    description: 'If `false` and the base version is a beta version (< 1.0.0), interpret major/breaking changes as increasing the version to the lowest non-beta version (1.0.0)'
    required: false
    default: 'true'

outputs:
  strand_url:
    description: 'The URL for the strand.'
  strand_version_url:
    description: 'The URL for the new strand version.'
  strand_version_uuid:
    description: 'The UUID of the new strand version.'

runs:
   using: 'docker'
   image: 'docker://octue/publish-strand-version:0.1.0-beta.1'
   args:
     - ${{ inputs.token }}
     - ${{ inputs.account }}
     - ${{ inputs.name }}
     - ${{ inputs.path }}
     - ${{ inputs.version }}
     - ${{ inputs.notes }}
     - ${{ input.allow_beta }}
