# This workflow will install the Python dependencies and run the tests.

name: python-ci

on:
  push:
    branches-ignore:
      - main

jobs:

  check-semantic-version:
    if: "!contains(github.event.head_commit.message, 'skipci')"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          # Set fetch-depth to 0 to fetch all tags (necessary for git-mkver to determine the correct semantic version).
          fetch-depth: 0
      - uses: octue/check-semantic-version@main
        with:
          path: pyproject.toml
          breaking_change_indicated_by: major

  tests:
    if: "!contains(github.event.head_commit.message, 'skipci')"
    runs-on: ubuntu-latest
    env:
      USING_COVERAGE: '3.12'
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.12'

      - name: Install Poetry
        uses: snok/install-poetry@v1

      - name: Install tox
        run: pip install tox

      - name: Run tests
        run: tox
