name: test-publish-strand-version

on:
  push:
    branches-ignore:
      - main

jobs:
  test-publish-strand-version:
    if: "!contains(github.event.head_commit.message, 'skipci')"
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Get release notes
        id: notes
        run: echo "release_notes=$(cat tests/schema/notes.md)" >> $GITHUB_OUTPUT

      - name: Publish strand version
        id: publish
        uses: octue/publish-strand-version@0.2.0
        with:
          token: ${{ secrets.STRANDS_TOKEN }}
          account: cortadocodes
          name: test-publish-strand-version
          path: tests/schema/schema.json
          notes: ${{ steps.notes.outputs.release_notes }}
          suggest_only: true
