name: test-publish-strand-version

on:
  push:
    paths:
      - tests/schema.json
    branches-ignore:
      - main

jobs:
  test-publish-strand-version:
    if: "!contains(github.event.head_commit.message, 'skipci')"
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Publish strand version
        id: publish
        uses: octue/publish-strand-version@update-api-usage
        with:
          token: ${{ secrets.STRANDS_TOKEN }}
          account: cortadocodes
          name: test-publish-strand-version
          path: tests/schema.json
          notes: Some test notes.

      - name: Print outputs
        run: |
          echo "Strand URL: ${{ steps.publish.outputs.strand_url }}"
          echo "Strand version URL: ${{ steps.publish.outputs.strand_version_url }}"
          echo "Strand version UUID: ${{ steps.publish.outputs.strand_version_uuid }}"
